# Generated by Django 2.0.4 on 2018-04-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('time', models.DateTimeField()),
                ('detail', models.TextField()),
                ('poster', models.ImageField(upload_to='img')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('max_peoples', models.IntegerField()),
                ('register_number', models.IntegerField()),
                ('review_number', models.IntegerField()),
                ('tickets', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(blank=True, choices=[('未发布', '未发布'), ('已结束', '已结束'), ('未开始', '未开始'), ('正在报名中', '正在报名中'), ('活动人数已满', '活动人数已满'), ('打折中', '打折中')], default='未发布', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventSituation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('userid', models.IntegerField()),
                ('usergroup', models.CharField(max_length=20)),
                ('eventid', models.IntegerField()),
                ('original_tickets', models.DecimalField(decimal_places=2, max_digits=20)),
                ('final_tickets', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(blank=True, choices=[('未参加', '未参加'), ('已参加', '已参加'), ('已报名', '已报名'), ('已通过审核', '已通过审核'), ('未通过审核', '未通过审核'), ('已通过审核但未参加', '已通过审核但未参加'), ('已取消', '已取消')], default='未参加', max_length=20)),
                ('explanation', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('userid', models.IntegerField()),
                ('usergroup', models.CharField(max_length=20)),
                ('eventid', models.IntegerField()),
                ('eventstatus', models.CharField(max_length=20)),
                ('reviewid', models.IntegerField()),
                ('reviewresult', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('eventid', models.IntegerField()),
                ('original_tickets', models.DecimalField(decimal_places=2, max_digits=20)),
                ('conditions', models.CharField(max_length=100)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
